---
- hosts: all
  become: yes
  tasks:
  - name: removing directory
    file:
  #    path: /home/ansible/{{ item }}
      path: /home/ansible/AnsibleZone
      state: absent
      recurse: no
#    with_fileglob:
 #       - "v"
