---
- hosts: localhost
  become: yes
  tasks:
  - name: install openjdk 8
    yum: 
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat7
    yum:
      name: tomcat
      state: present
  - name: download jenkins to webapps folder
    get_url:
      url:  https://updates.jenkins-ci.org/download/war/2.149/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
