- hosts: node
  become: yes
  tasks:
  - name: Add apt repository
    apt_repository:
      repo: 'ppa:webupd8team/java'
      state: present
      update_cache: yes

  - name: Accept license
    debconf:
     name: 'oracle-java8-installer'
     question: 'shared/accepted-oracle-license-v1-1'
     value: 'true'
     vtype: 'select'

  - name: Install java
    apt: name={{ item }} state=present
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
  - name: java path setting
    lineinfile:
      dest: /etc/environment
      line: 'export JAVA_HOME="/usr/lib/jvm/java-8-oracle"' 
  - name: setting maven path upto bin
    lineinfile:
      dest: /etc/environment
      line: 'export PATH=$PATH:$JAVA_HOME/bin'