---
- hosts: all
  become: yes
  tasks:
  - name: installing git
    apt:
      name: git
      state: present
  - name: aading java ppa repo
    apt_repository:
      repo: ppa:webupd8team/java
    notify: apt-get update
  - name: installing java 8 
    debconf:
      name: oracle-java8-installer
      question: shared/accepted-oracle-licence-v1-1
      value: 'true'
      vtype: select
    notify: apt-get update
  handlers:
  - name: apt-get update
    apt:
      update_cache: yes
  