---
- hosts: localhost
  become: yes
  tasks:
  - name: install openjdk 8
    apt: 
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat7
    apt:
      name: tomcat
      state: present
  - name: download jenkins to webapps folder
    get_url:
      url:  https://downloads.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.0.4.1/openmrs.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
