--- 
- hosts: all 
  become: yes 
  tasks: 
  - name: Ensure ansible user exists 
    user: 
      name: john 
      state: present 
      comment: Ansible 
  - name: Ensure ansible user accepts the SSH key 
    authorized_key: 
      user: ansible 
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      state: present 
  - name: Ensure the ansible user is sudoer with no password required 
    lineinfile: 
      dest: /etc/sudoers 
      state: present 
      regexp: '^%ADMIN ALL=' 
      line: '%john ALL=(ALL) NOPASSWD: ALL' 
      validate: '/usr/sbin/visudo -cf %s'
