---
- hosts: all
  become: yes
  tasks:
    - stat:
        path: /home/centos/ansible
      register: samplefile
    - package:
        name: httpd
        state: present
      when: samplefile.stat.exists
    - service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
