---
- hosts: all
  become: yes
  tasks:
    - stat:
        path: /home/centos/ansible
      register: samplefile
    - debug:
        msg: "file exists"
      when: samplefile.stat.exists
    - package:
        name: httpd
        state: present
      when: samplefile.stat.exists
# we can also user isdir,islink to check the path is directory or link
# when: samplefile.stat.isdir || when: samplefile.stat.islink
    - service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        
        ----------------------------
        
        --- 
        //https://www.middlewareinventory.com/blog/ansible-changed_when-and-failed_when-examples//
- hosts: web
  tasks:
  - name: "Determine if the HTTPD is installed"
    register: validatehttpd
    shell: httpd

  - name: Ensure Apache is at the Latest version
    become: yes
    become_user: root
    yum:
      name: httpd
      state: latest
    when: 'not found' in validatehttpd.stdout
    
